### ISSUE TITLE
Keras implementation of GAN models

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [wiseodd/generative-models#1]
Cold you please provide implementation of GAN models in Keras besides tensorflow and pytorch?

**Comment by wiseodd** [comment]
That's a very low priority item for me.
However, feel free to send me a pull request if you want to contribute.

**Comment by ErmiaAzarkhalili** [comment]
It's so pity, I urgently need it in one important application. I have no idea why you left keras and chose TF as Keras is more easy to utilize. BTW, your code was very very helpful, Hope you reconsider my request.

**Comment by wiseodd** [comment]
I'm focusing on Pytorch and Tensorflow implementations.
Hence, I won't use Keras anymore.

If anyone interested, feel free to send me pull requests for Keras implementations.
