### ISSUE TITLE
problems of vallina GAN 

### ISSUE THREAD

**Issue by Jiakui** [wiseodd/generative-models#10]
I tried the vanilla GAN without any modification of your code, but there was always mode collapse happening. What's the possible reason for mode collapse in vanilla GAN? 

Thanks

**Comment by wiseodd** [comment]
You could try to match the networks' architecture with the original paper.
Also, there are some "hacks" that might just work, see: https://github.com/soumith/ganhacks.
Fundamentally, that question itself is still an open research problem.

**Comment by AshishBora** [comment]
+1
I am also seeing mode collapse.
