### ISSUE TITLE
Problems of WGAN

### ISSUE THREAD

**Issue by Jiakui** [wiseodd/generative-models#11]
WGAN seems really slow, I tried your code with 10 million iterations, but the output images still looks very bad. 

Do you have any idea?

Thanks!

**Comment by wiseodd** [comment]
Indeed WGAN seems slow to converge. This is also observed in the original paper.
As for the quality of the samples, considering all of the codes here use two layer net, you are encouraged to try and explore different network architecture (e.g. deconv net for G and CNN for D).

**Comment by tcglarry** [comment]
In the code , did you use Wasserstein to count the distance between discriminator and generator ?
I can't see the algorithm of it, could you shed  a light ? Thanks
