### ISSUE TITLE
WGAN Wasserstein algorithm

### ISSUE THREAD

**Issue by tcglarry** [wiseodd/generative-models#12]
In the code , did you use Wasserstein to count the distance between discriminator and generator ?
I can't see the algorithm of it, could you shed  a light ? Thanks

**Comment by wiseodd** [comment]
See Algorithm 1 in the paper: https://arxiv.org/abs/1701.07875

**Comment by livey** [comment]
Should  G_loss and D_loss be the opposite sign, because we are maximize the objective value?

**Comment by wiseodd** [comment]
Exactly because we're doing maximization, the signs are like that, i.e. negative.

**Comment by livey** [comment]
I see, you take the negative sign in the optimizer. Thank you.

**Comment by tcglarry** [comment]
Hi, ...tks for this post and advise,,,,,I checked the paper, and got he idea that it only needs to take out "log' in the loss function , no need to apply sigmoid, and plus add clipping. 

however,  I do have some strange feeling ....JS divergence(normal GAN) vs Earth Moving distance (WGAN) is so different, but to realize it, juts take out 'log'......why no need to implement the algorithm of 'real' EM distance ? 

tks 
Larry
