### ISSUE TITLE
generation of vanilla_gan at the end are all 1-s

### ISSUE THREAD

**Issue by stoneyang** [wiseodd/generative-models#14]
Hi, @wiseodd ,

Thanks for your cool implementation of these models! 

I'm a newbie to GANs and tensorflow. 
I've tried vanilla gan by running `gan_tensorflow.py`. 

At the end of training, the content of G becomes all 1-s, ie, all the squares just contain the image of number one, not like the snapshot in the mid-term of the training, all numbers are generated.  

Are these results correct? How to explain it? Thanks in advance!

Best regards.

**Comment by wiseodd** [comment]
Hi @stoneyang,
It's a problem with GAN, called mode collapse, where the distribution of G is collapsing to a delta function (1 in one place, and 0 everywhere else; think of gaussian when variance goes to zero). That's why you get only identical (constant) samples.

**Comment by stoneyang** [comment]
Thank you for pointing out mode collapse. 

Seems the later work Wasserstein GAN is one of the work to solve this problem. Fortunately there is a tf implementation in this repo, I'll try it and study the original paper. Found GAN family's are interesting.

**Comment by wiseodd** [comment]
Yes, majority of GAN papers (that focus on the algorithm) are motivated by mode collapse problem.
