### ISSUE TITLE
continuous latent code for infogan

### ISSUE THREAD

**Issue by kudo1026** [wiseodd/generative-models#16]
Hi,

First of all, thanks so much for these great scripts for for the GANs. They are easy to implement so that I can start off my research. But I have one question in your infogan script. In the code, you use a 10-binary-digit array as your c_noise, the latent code for the generator. There's no problem with it if you only want to use discrete latent code, but what if you want continuous latent code(which was implemented in the original infogan paper)? Or more generally, how do you choose to represent your z_noise and c_noise?

Thanks

**Comment by wiseodd** [comment]
Hi,
I haven't experimented with that, but check out appendix C on the paper, they have some information about it. Basically you need to parameterized the Q network with gaussian mean and variance, similar to VAE's inference net.
Also refer to OpenAI's implementation https://github.com/openai/InfoGAN.
