### ISSUE TITLE
CelebA and other datasets

### ISSUE THREAD

**Issue by npark** [wiseodd/generative-models#19]
Hello,
Thanks for your work.

Do you have a plan to integrate with other datasets? MNIST is the easiest one to use but there are many other meaningful datasets such as CelebA. It would be nice if you can provide some codes to test other datasets.

**Comment by wiseodd** [comment]
Hi,

Currently, I don’t have any plan to do that due to time constraint.
However, as always, if anybody, including you, want to contribute on that, just create a pull request. It is always welcomed.
