### ISSUE TITLE
About Mode regularized GAN

### ISSUE THREAD

**Issue by zhangqianhui** [wiseodd/generative-models#23]
Your code about trainig process is very different from the details in the paper(MD GAN)

MDGAN in the original paper must train in the manifold step and the diffusion step.

And the loss also has the differences.

I'm wrong?

**Comment by wiseodd** [comment]
Hi, sorry for very long delay.
Implementation in this repo is following Eq. 1 and 2 in Section 3.2.
Hope this clears up the confusion.
