### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by ArghyaPal** [wiseodd/generative-models#26]
Hi, 
I have got an error while running 
`python infogan_pytorch.py`

`Extracting ../../MNIST_data/train-images-idx3-ubyte.gz
Extracting ../../MNIST_data/train-labels-idx1-ubyte.gz
Extracting ../../MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../../MNIST_data/t10k-labels-idx1-ubyte.gz
/home/arghyapal/miniconda2/envs/generative-models/lib/python3.5/site-packages/torch/optim/adam.py:74: UserWarning: tensor1 is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  p.data.addcdiv_(-step_size, exp_avg, denom)
Traceback (most recent call last):
  File "infogan_pytorch.py", line 119, in <module>
    reset_grad()
  File "infogan_pytorch.py", line 86, in reset_grad
    p.grad.data.zero_()
AttributeError: 'NoneType' object has no attribute 'data'`

Please help me...!!!

**Comment by wiseodd** [comment]
It might be because of API change on newer pytorch.
I will check it when I have spare time.

**Comment by jbmaxwell** [comment]
Same error here. Any update or fix?

**Comment by wiseodd** [comment]
Hi, you have two options.

**First one (hacky way):**
Change the `reset_grad()` function to this:
``` python
def reset_grad():
    for p in params:
        if p.grad is not None:
            data = p.grad.data
            p.grad = Variable(data.new().resize_as_(data).zero_())
```

**Second one (best way):**
Use `torch.nn` module to built the nets. Please see how it's done in https://github.com/wiseodd/generative-models/blob/master/GAN/least_squares_gan/lsgan_pytorch.py for example.

The `reset_grad()` function is then just:
``` python
def reset_grad():
    G.zero_grad()
    D.zero_grad()
```
