### ISSUE TITLE
dualgan does not work

### ISSUE THREAD

**Issue by Junjun2016** [wiseodd/generative-models#27]
I have run dualgan, but it does not work, just generated noise images.

I checked the code carefully with the paper, it matched, but I am still confused about the G_loss.

I have  debugged for a long time, but it's still not work.

Could you please give me some help, and check the code?

**Comment by warisha** [comment]
i have same problem,
Can you please help me ?
I have tried to debug it but it generate noise images. please help me!

![untitled](https://user-images.githubusercontent.com/18666252/29772384-fbbf27be-8c11-11e7-952f-2455002a57fc.png)

**Comment by wiseodd** [comment]
Considering everything in this repo is just simple 2 layers MLP, you should try using the architecture stated in the paper.
