### ISSUE TITLE
recon_loss term in AVB implementation

### ISSUE THREAD

**Issue by JulienSiems** [wiseodd/generative-models#3]
I didn't understand where you get the recon_loss term in the AVB implementation from. 
I couldn't find it anywhere in the paper. 

Amazing repo by the way!

**Comment by wiseodd** [comment]
That's for the last term in equation 3.9 in the paper.
Or, you could check line 6 of the algorithm in Section 3.2.

**Comment by JulienSiems** [comment]
Cool thanks makes sense!
