### ISSUE TITLE
AAE-LSTM

### ISSUE THREAD

**Issue by pedrofale** [wiseodd/generative-models#30]
Hello Augustus,

Thank you very much for your code. I am trying to change the Adversarial Autoencoder to use LSTM layers. Have you tried this? Do you think it would work? So far I haven't been able to make it converge.

Thanks!

**Comment by wiseodd** [comment]
Hi,

I haven’t tried using RNN for GAN.
However, you might want to look at this paper: https://arxiv.org/abs/1602.05110 <https://arxiv.org/abs/1602.05110>.
In theory GAN as a framework could be used regardless the model we choose for generator/discriminator.

Cheers.

**Comment by pedrofale** [comment]
Thanks!
