### ISSUE TITLE
Problem: AttributeError: 'Tensor' object has no attribute 'next_batch'

### ISSUE THREAD

**Issue by warisha** [wiseodd/generative-models#33]
please help me. i am unable to understand how to feed values of x_mb, y_mb for my own dataset instead of mnist.

![untitled](https://user-images.githubusercontent.com/18666252/29651874-410625a6-88bc-11e7-9e5a-eaf46a3f207e.png)

**Comment by wiseodd** [comment]
Hi,

It depends on your dataset, `X.train.next_batch(mb_size)` likely will only work with MNIST.
I won't be able to help with this, so please consult your dataset's maintainer.
