### ISSUE TITLE
Coupled GAN display noise only

### ISSUE THREAD

**Issue by warisha** [wiseodd/generative-models#36]
I have used coupled GAN code for my own customize dataset. Discriminator and generator loss not decrease or increase and output noise only. I am unable to understand what is the real problem.
Can you please help me ?
I have tried to debug it but it generate noise images. please help me!
Same generator and discriminator loss.
![untitled](https://user-images.githubusercontent.com/18666252/29774689-d2ffd67a-8c1b-11e7-95a0-1d974209d635.png)

**Comment by LukasMosser** [comment]
Maybe your input data isn't normalized properly?

**Comment by wiseodd** [comment]
Have you experimented with vanilla GAN using your data?
Is it also only generating noise?

**Comment by wiseodd** [comment]
It would be better for you to ask the paper's authors.
They would definitely know more.
