### ISSUE TITLE
Addition to the GAN collection

### ISSUE THREAD

**Issue by spurra** [wiseodd/generative-models#48]
Hi,
If its possible, could you please add our variant of GAN to your collection too? It's a semi-supervised version of infoGAN. Thanks!

https://arxiv.org/abs/1707.04487

**Comment by wiseodd** [comment]
If you'd like to add new algorithms, feel free to create pull request.
I'd be happy to merge it.

-------- Original Message --------

**Comment by spurra** [comment]
Hmm I just realized that our code is written in torch unfortunately and the code collection you have is written in pyTorch/Tensorflow. If this is an issue for you, I understand.

**Comment by wiseodd** [comment]
I prefer the codes to be homogenous in PyTorch/TensorFlow as those are the most common ones.
If you'd like to write a simple minimal example about your method (using MNIST, as with other methods) in PyTorch and/or TensorFlow, I'd be glad to incorporate it in this repo.

Unfortunately I could not do it myself as I don't have time anymore to work on this repo.

-------- Original Message --------
