### ISSUE TITLE
what's the use of symbol '@' in line 40,41

### ISSUE THREAD

**Issue by jehovahxu** [wiseodd/generative-models#51]
May  i use python 3?

**Comment by mayorx** [comment]
I think it is a matrix multiplication operator
you can check [here](https://www.quora.com/What-does-do-in-Python-I-am-trying-to-understand-a-code-written-by-someone-else-It-has-a-part-1-def-kinetic-k-g-2-v-k-+-g-3-return-KINETIC_CONSTANT-*-v-v) or [here](https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-465) for detail.

**Comment by wiseodd** [comment]
Thanks @mayorx, you're correct.
That's a matmul operator introduced in Python 3.5, so @jehovahxu you must use Python 3.5+.

**Comment by jehovahxu** [comment]
thank you vary much for solving my confusion！
