### ISSUE TITLE
InfoGAN: Q_loss question

### ISSUE THREAD

**Issue by andreazanetti** [wiseodd/generative-models#61]
Hi, great work and repo. I have one question about the way the Qloss is computed in infoGAN [here](https://github.com/wiseodd/generative-models/blob/master/GAN/infogan/infogan_tensorflow.py#L104)
`ent = tf.reduce_mean(-tf.reduce_sum(tf.log(c + 1e-8) * c, 1))`
To me, log(c) is not correct there. 
I guess it should be log(P(c)), so log(0.1) in this implementation. 
With that, the Qloss value than reach the 2.3 of H(c) mentioned in the paper.
Does it make sense? Thanks

**Comment by wiseodd** [comment]
Just re-check the paper. It seems the entropy is over the prior. So it's a constant, and we can remove that.

**Comment by andreazanetti** [comment]
True, H(c) it is a constant and can be removed. If however one wants to replicate the result shown in the first part of the paper (fig.1), that could stay :) 
With reference to this, I am interested in extending the example to real-valued codes (say, you are simulating c1 from Cat(10) from the paper, but they also show the effect of adding 2 codes, c2,c3 from U(-1,1))
However, I am not yet clear about how to shape Q in this case, and how to compute the mutual information between real-valued (c2 and c3) and discrete variable (G(c1,c2,c3, z)).  Suggestions would be welcome, thanks!

**Comment by wiseodd** [comment]
I haven't tried that. But the paper indicates that we use different network for different c_i, then compute the MI lower bound for each, and add (or average) them together.
