### ISSUE TITLE
Port TensorFlow codes to v1.0

### ISSUE THREAD

**Issue by vinthony** [wiseodd/generative-models#7]
Hello,
I read your blog about cGAN, it's awesome.
and I want to run the code about it using tensorflow.
But here are some mistake under my Ubuntu 16.04 desktop.

1. According to the document of [tensorflow](https://www.tensorflow.org/api_docs/python/tf/concat). I modify the code from 
```python
 tf.concat(concat_dim=1, values=[z, y])
# to 
tf.concat([z,y],1);
# in line 37 and 58
```

2. there is also a new API design for `sigmoid_cross_entropy_with_logits`:
```python
#line 90,91
D_loss_real = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(D_logit_real, tf.ones_like(D_logit_real)))
D_loss_fake = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(D_logit_fake, tf.zeros_like(D_logit_fake)))
#to 
D_loss_real = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=D_logit_real, labels=tf.ones_like(D_logit_real)))
D_loss_fake = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=D_logit_fake, labels=tf.zeros_like(D_logit_fake)))
```

then the code runs.

Although these API changes would not have the influence the understanding of algorithm.
But I think it will help the people who want to run the code and newly to Tensorflow.

**Comment by wiseodd** [comment]
Unfortunately, this is due to TensorFlow version 1.0 making API changes, which makes it not backward compatible.

I agree though, all the TF codes should be ported to v1.0 as soon as possible.
I will keep this issue open until then.

**Comment by wiseodd** [comment]
Scripts for TensorFlow v1.0+ has been added via 01049cdc5f4cb9d2a5d248c37580d063a2dd8be9
